<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'label' => 'Dashboard',
                'url' => 'dashboard',
                'icon' => '<i class="nav-icon la la-dashboard "></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 2,
                'rgt' => 3,
                'depth' => 1,
                'created_at' => '2020-12-16 06:58:25',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            1 => 
            array (
                'id' => 2,
                'label' => 'Employee Records',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-user"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 4,
                'rgt' => 33,
                'depth' => 1,
                'created_at' => '2020-12-16 07:00:21',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            2 => 
            array (
                'id' => 3,
                'label' => 'Awards & Recog.',
                'url' => 'awardandrecognition',
                'icon' => '<i class=\'nav-icon la la-trophy\'></i>',
                'permission' => 'award_and_recognitions_list',
                'parent_id' => 2,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 2,
                'created_at' => '2020-12-16 07:11:38',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            3 => 
            array (
                'id' => 4,
                'label' => 'Employees',
                'url' => 'employee',
                'icon' => '<i class=\'nav-icon la la-user-plus\'></i>',
                'permission' => 'employees_list',
                'parent_id' => 2,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 2,
                'created_at' => '2020-12-16 07:12:30',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            4 => 
            array (
                'id' => 5,
                'label' => 'Gov. Exams',
                'url' => 'governmentexamination',
                'icon' => '<i class=\'nav-icon la la-industry\'></i>',
                'permission' => 'government_examinations_list',
                'parent_id' => 2,
                'lft' => 19,
                'rgt' => 20,
                'depth' => 2,
                'created_at' => '2020-12-16 07:13:14',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            5 => 
            array (
                'id' => 6,
                'label' => 'Supporting Docs.',
                'url' => 'supportingdocument',
                'icon' => '<i class=\'nav-icon la la-file-alt\'></i>',
                'permission' => 'supporting_documents_list',
                'parent_id' => 2,
                'lft' => 27,
                'rgt' => 28,
                'depth' => 2,
                'created_at' => '2020-12-16 07:13:57',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            6 => 
            array (
                'id' => 7,
                'label' => 'Training & Seminars',
                'url' => 'trainingandseminar',
                'icon' => '<i class=\'nav-icon la la-bicycle\'></i>',
                'permission' => 'training_and_seminars_list',
                'parent_id' => 2,
                'lft' => 29,
                'rgt' => 30,
                'depth' => 2,
                'created_at' => '2020-12-16 07:20:23',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            7 => 
            array (
                'id' => 8,
                'label' => 'Work Experiences',
                'url' => 'workexperience',
                'icon' => '<i class=\'nav-icon la la-bolt\'></i>',
                'permission' => 'work_experiences_list',
                'parent_id' => 2,
                'lft' => 31,
                'rgt' => 32,
                'depth' => 2,
                'created_at' => '2020-12-16 07:20:46',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            8 => 
            array (
                'id' => 9,
                'label' => 'App Settings',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-cog"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 44,
                'rgt' => 99,
                'depth' => 1,
                'created_at' => '2020-12-16 07:21:07',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            9 => 
            array (
                'id' => 10,
                'label' => 'Blood Type',
                'url' => 'bloodtype',
                'icon' => '<i class=\'nav-icon la la-eyedropper\'></i>',
                'permission' => 'blood_types_list',
                'parent_id' => 9,
                'lft' => 49,
                'rgt' => 50,
                'depth' => 2,
                'created_at' => '2020-12-16 07:21:32',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            10 => 
            array (
                'id' => 11,
                'label' => 'Citizenship',
                'url' => 'citizenship',
                'icon' => '<i class=\'nav-icon la la-flag-o\'></i>',
                'permission' => 'citizenships_list',
                'parent_id' => 9,
                'lft' => 51,
                'rgt' => 52,
                'depth' => 2,
                'created_at' => '2020-12-16 07:21:51',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            11 => 
            array (
                'id' => 12,
                'label' => 'Civil Status',
                'url' => 'civilstatus',
                'icon' => '<i class=\'nav-icon la la-neuter\'></i>',
                'permission' => 'civil_statuses_list',
                'parent_id' => 9,
                'lft' => 53,
                'rgt' => 54,
                'depth' => 2,
                'created_at' => '2020-12-16 07:22:14',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            12 => 
            array (
                'id' => 13,
                'label' => 'Gender',
                'url' => 'gender',
                'icon' => '<i class=\'nav-icon la la-venus\'></i>',
                'permission' => 'genders_list',
                'parent_id' => 9,
                'lft' => 69,
                'rgt' => 70,
                'depth' => 2,
                'created_at' => '2020-12-16 07:22:32',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            13 => 
            array (
                'id' => 14,
                'label' => 'Religion',
                'url' => 'religion',
                'icon' => '<i class=\'nav-icon la la-church\'></i>',
                'permission' => 'religions_list',
                'parent_id' => 9,
                'lft' => 93,
                'rgt' => 94,
                'depth' => 2,
                'created_at' => '2020-12-16 07:22:56',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            14 => 
            array (
                'id' => 15,
                'label' => 'Administrator Only',
                'url' => NULL,
                'icon' => NULL,
                'permission' => 'admin_view',
                'parent_id' => NULL,
                'lft' => 100,
                'rgt' => 101,
                'depth' => 1,
                'created_at' => '2020-12-16 07:23:11',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            15 => 
            array (
                'id' => 16,
                'label' => 'Audit Trails',
                'url' => 'audittrail',
                'icon' => '<i class=\'nav-icon la la-history\'></i>',
                'permission' => 'audit_trails_list',
                'parent_id' => NULL,
                'lft' => 102,
                'rgt' => 103,
                'depth' => 1,
                'created_at' => '2020-12-16 07:26:27',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            16 => 
            array (
                'id' => 17,
                'label' => 'Authentication',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-users"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 104,
                'rgt' => 111,
                'depth' => 1,
                'created_at' => '2020-12-16 07:27:02',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            17 => 
            array (
                'id' => 18,
                'label' => 'Users',
                'url' => 'user',
                'icon' => '<i class="nav-icon la la-user"></i>',
                'permission' => 'users_list',
                'parent_id' => 17,
                'lft' => 105,
                'rgt' => 106,
                'depth' => 2,
                'created_at' => '2020-12-16 07:27:32',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            18 => 
            array (
                'id' => 19,
                'label' => 'Roles',
                'url' => 'role',
                'icon' => '<i class="nav-icon la la-id-badge"></i>',
                'permission' => 'roles_list',
                'parent_id' => 17,
                'lft' => 107,
                'rgt' => 108,
                'depth' => 2,
                'created_at' => '2020-12-16 07:27:49',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            19 => 
            array (
                'id' => 20,
                'label' => 'Permissions',
                'url' => 'permission',
                'icon' => '<i class="nav-icon la la-key"></i>',
                'permission' => 'permissions_list',
                'parent_id' => 17,
                'lft' => 109,
                'rgt' => 110,
                'depth' => 2,
                'created_at' => '2020-12-16 07:28:08',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            20 => 
            array (
                'id' => 21,
                'label' => 'Advanced',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-cogs"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 112,
                'rgt' => 121,
                'depth' => 1,
                'created_at' => '2020-12-16 07:28:27',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            21 => 
            array (
                'id' => 22,
                'label' => 'File Manager',
                'url' => 'elfinder',
                'icon' => '<i class="nav-icon la la-files-o"></i>',
                'permission' => 'advanced_file_manager',
                'parent_id' => 21,
                'lft' => 113,
                'rgt' => 114,
                'depth' => 2,
                'created_at' => '2020-12-16 07:30:40',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            22 => 
            array (
                'id' => 23,
                'label' => 'Backups',
                'url' => 'backup',
                'icon' => '<i class=\'nav-icon la la-hdd-o\'></i>',
                'permission' => 'advanced_backups',
                'parent_id' => 21,
                'lft' => 115,
                'rgt' => 116,
                'depth' => 2,
                'created_at' => '2020-12-16 07:31:21',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            23 => 
            array (
                'id' => 24,
                'label' => 'Logs',
                'url' => 'log',
                'icon' => '<i class=\'nav-icon la la-terminal\'></i>',
                'permission' => 'advanced_logs',
                'parent_id' => 21,
                'lft' => 117,
                'rgt' => 118,
                'depth' => 2,
                'created_at' => '2020-12-16 07:31:47',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            24 => 
            array (
                'id' => 25,
                'label' => 'Settings',
                'url' => 'setting',
                'icon' => '<i class=\'nav-icon la la-cog\'></i>',
                'permission' => 'advanced_settings',
                'parent_id' => 21,
                'lft' => 119,
                'rgt' => 120,
                'depth' => 2,
                'created_at' => '2020-12-16 07:32:02',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            25 => 
            array (
                'id' => 26,
                'label' => 'Menu',
                'url' => 'menu',
                'icon' => '<i class=\'nav-icon la la-list\'></i>',
                'permission' => 'menus_list',
                'parent_id' => NULL,
                'lft' => 122,
                'rgt' => 123,
                'depth' => 1,
                'created_at' => '2020-12-16 07:32:42',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            26 => 
            array (
                'id' => 28,
                'label' => 'Family & Contacts',
                'url' => 'familydata',
                'icon' => '<i class=\'nav-icon las la-clone\'></i>',
                'permission' => 'family_datas_list',
                'parent_id' => 2,
                'lft' => 17,
                'rgt' => 18,
                'depth' => 2,
                'created_at' => '2020-12-31 09:52:25',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            27 => 
            array (
                'id' => 29,
                'label' => 'Relation',
                'url' => 'relation',
                'icon' => '<i class=\'nav-icon las la-clone\'></i>',
                'permission' => 'relations_list',
                'parent_id' => 9,
                'lft' => 91,
                'rgt' => 92,
                'depth' => 2,
                'created_at' => '2021-01-05 02:25:36',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            28 => 
            array (
                'id' => 30,
                'label' => 'Educational Level',
                'url' => 'educationallevel',
                'icon' => '<i class="nav-icon las la-graduation-cap"></i>',
                'permission' => 'educational_levels_list',
                'parent_id' => 9,
                'lft' => 63,
                'rgt' => 64,
                'depth' => 2,
                'created_at' => '2021-01-07 05:08:46',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            29 => 
            array (
                'id' => 31,
                'label' => 'Educational Bg.',
                'url' => 'educationalbackground',
                'icon' => '<i class=\'nav-icon las la-graduation-cap\'></i>',
                'permission' => 'educational_backgrounds_list',
                'parent_id' => 2,
                'lft' => 13,
                'rgt' => 14,
                'depth' => 2,
                'created_at' => '2021-01-07 05:47:39',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            30 => 
            array (
                'id' => 32,
                'label' => 'Medical Information',
                'url' => 'medicalinformation',
                'icon' => '<i class=\'nav-icon la la-medkit\'></i>',
                'permission' => 'medical_informations_list',
                'parent_id' => 2,
                'lft' => 21,
                'rgt' => 22,
                'depth' => 2,
                'created_at' => '2021-01-07 10:04:28',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            31 => 
            array (
                'id' => 33,
                'label' => 'Professional Org.',
                'url' => 'professionalorg',
                'icon' => '<i class=\'nav-icon la la-address-card\'></i>',
                'permission' => 'professional_orgs_list',
                'parent_id' => 2,
                'lft' => 23,
                'rgt' => 24,
                'depth' => 2,
                'created_at' => '2021-01-07 12:43:27',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            32 => 
            array (
                'id' => 34,
                'label' => 'Beneficiaries',
                'url' => 'beneficiary',
                'icon' => '<i class=\'nav-icon la la-user-shield\'></i>',
                'permission' => 'benefeciaries_list',
                'parent_id' => 2,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 2,
                'created_at' => '2021-01-08 07:10:38',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            33 => 
            array (
                'id' => 35,
                'label' => 'Dependents',
                'url' => 'dependents',
                'icon' => '<i class=\'nav-icon las la-baby\'></i>',
                'permission' => 'dependents_list',
                'parent_id' => 2,
                'lft' => 11,
                'rgt' => 12,
                'depth' => 2,
                'created_at' => '2021-01-09 07:52:23',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            34 => 
            array (
                'id' => 36,
                'label' => 'Skills & Talents',
                'url' => 'skillandtalent',
                'icon' => '<i class=\'nav-icon las la-music\'></i>',
                'permission' => 'skill_and_talents_list',
                'parent_id' => 2,
                'lft' => 25,
                'rgt' => 26,
                'depth' => 2,
                'created_at' => '2021-01-09 11:08:45',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            35 => 
            array (
                'id' => 37,
                'label' => 'Payment Method',
                'url' => 'paymentmethod',
                'icon' => '<i class=\'nav-icon las la-credit-card\'></i>',
                'permission' => 'payment_methods_list',
                'parent_id' => 9,
                'lft' => 85,
                'rgt' => 86,
                'depth' => 2,
                'created_at' => '2021-01-11 09:58:11',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            36 => 
            array (
                'id' => 38,
                'label' => 'Pay Basis',
                'url' => 'paybasis',
                'icon' => '<i class=\'nav-icon las la-calendar-alt\'></i>',
                'permission' => 'pay_bases_list',
                'parent_id' => 9,
                'lft' => 83,
                'rgt' => 84,
                'depth' => 2,
                'created_at' => '2021-01-12 04:58:02',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            37 => 
            array (
                'id' => 39,
                'label' => 'Job Status',
                'url' => 'jobstatus',
                'icon' => '<i class=\'nav-icon las la-user-tag\'></i>',
                'permission' => 'job_statuses_list',
                'parent_id' => 9,
                'lft' => 75,
                'rgt' => 76,
                'depth' => 2,
                'created_at' => '2021-01-12 05:36:56',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            38 => 
            array (
                'id' => 40,
                'label' => 'Employment Status',
                'url' => 'employmentstatus',
                'icon' => '<i class=\'nav-icon las la-user-tie\'></i>',
                'permission' => 'employment_statuses_list',
                'parent_id' => 9,
                'lft' => 67,
                'rgt' => 68,
                'depth' => 2,
                'created_at' => '2021-01-12 07:05:31',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            39 => 
            array (
                'id' => 41,
                'label' => 'Company',
                'url' => 'company',
                'icon' => '<i class=\'nav-icon las la-building\'></i>',
                'permission' => 'companies_list',
                'parent_id' => 9,
                'lft' => 55,
                'rgt' => 56,
                'depth' => 2,
                'created_at' => '2021-01-12 07:30:05',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            40 => 
            array (
                'id' => 42,
                'label' => 'Location',
                'url' => 'location',
                'icon' => '<i class=\'nav-icon las la-map-marked-alt\'></i>',
                'permission' => 'locations_list',
                'parent_id' => 9,
                'lft' => 79,
                'rgt' => 80,
                'depth' => 2,
                'created_at' => '2021-01-12 10:59:14',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            41 => 
            array (
                'id' => 43,
                'label' => 'Department',
                'url' => 'department',
                'icon' => '<i class=\'nav-icon las la-layer-group\'></i>',
                'permission' => 'departments_list',
                'parent_id' => 9,
                'lft' => 59,
                'rgt' => 60,
                'depth' => 2,
                'created_at' => '2021-01-12 13:29:06',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            42 => 
            array (
                'id' => 44,
                'label' => 'Division',
                'url' => 'division',
                'icon' => '<i class=\'nav-icon las la-star-half-alt\'></i>',
                'permission' => 'divisions_list',
                'parent_id' => 9,
                'lft' => 61,
                'rgt' => 62,
                'depth' => 2,
                'created_at' => '2021-01-12 13:44:42',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            43 => 
            array (
                'id' => 45,
                'label' => 'Section',
                'url' => 'section',
                'icon' => '<i class=\'nav-icon las la-stream\'></i>',
                'permission' => 'sections_list',
                'parent_id' => 9,
                'lft' => 95,
                'rgt' => 96,
                'depth' => 2,
                'created_at' => '2021-01-12 15:29:49',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            44 => 
            array (
                'id' => 46,
                'label' => 'Position',
                'url' => 'position',
                'icon' => '<i class=\'nav-icon las la-hard-hat\'></i>',
                'permission' => 'positions_list',
                'parent_id' => 9,
                'lft' => 87,
                'rgt' => 88,
                'depth' => 2,
                'created_at' => '2021-01-13 04:50:01',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            45 => 
            array (
                'id' => 47,
                'label' => 'Level',
                'url' => 'level',
                'icon' => '<i class=\'nav-icon las la-balance-scale\'></i>',
                'permission' => 'levels_list',
                'parent_id' => 9,
                'lft' => 77,
                'rgt' => 78,
                'depth' => 2,
                'created_at' => '2021-01-13 23:10:39',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            46 => 
            array (
                'id' => 48,
                'label' => 'Rank',
                'url' => 'rank',
                'icon' => '<i class=\'nav-icon las la-chalkboard\'></i>',
                'permission' => 'ranks_list',
                'parent_id' => 9,
                'lft' => 89,
                'rgt' => 90,
                'depth' => 2,
                'created_at' => '2021-01-13 23:30:25',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            47 => 
            array (
                'id' => 49,
                'label' => 'Grouping',
                'url' => 'grouping',
                'icon' => '<i class=\'nav-icon las la-object-group\'></i>',
                'permission' => 'groupings_list',
                'parent_id' => 9,
                'lft' => 73,
                'rgt' => 74,
                'depth' => 2,
                'created_at' => '2021-01-14 14:24:53',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            48 => 
            array (
                'id' => 50,
                'label' => 'Days Per Year',
                'url' => 'daysperyear',
                'icon' => '<i class=\'nav-icon las la-calendar\'></i>',
                'permission' => 'days_per_years_list',
                'parent_id' => 9,
                'lft' => 57,
                'rgt' => 58,
                'depth' => 2,
                'created_at' => '2021-01-16 02:11:31',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            49 => 
            array (
                'id' => 51,
                'label' => 'Employment Info',
                'url' => 'employmentinformation',
                'icon' => '<i class=\'nav-icon las la-address-book\'></i>',
                'permission' => 'employment_informations_list',
                'parent_id' => 2,
                'lft' => 15,
                'rgt' => 16,
                'depth' => 2,
                'created_at' => '2021-01-18 06:07:20',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            50 => 
            array (
                'id' => 52,
                'label' => 'Emp. Info Field',
                'url' => 'employmentinfofield',
                'icon' => '<i class=\'nav-icon las la-table\'></i>',
                'permission' => 'employment_info_fields_list',
                'parent_id' => 9,
                'lft' => 65,
                'rgt' => 66,
                'depth' => 2,
                'created_at' => '2021-01-21 16:45:46',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            51 => 
            array (
                'id' => 53,
                'label' => 'Performance Mgt.',
                'url' => NULL,
                'icon' => '<i class="nav-icon las la-chalkboard"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 34,
                'rgt' => 39,
                'depth' => 1,
                'created_at' => '2021-01-28 14:40:46',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            52 => 
            array (
                'id' => 54,
                'label' => 'Per. Appraisal',
                'url' => 'performanceappraisal',
                'icon' => '<i class=\'nav-icon la la-hands-helping\'></i>',
                'permission' => 'performance_appraisals_list',
                'parent_id' => 53,
                'lft' => 37,
                'rgt' => 38,
                'depth' => 2,
                'created_at' => '2021-01-28 14:51:05',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            53 => 
            array (
                'id' => 55,
                'label' => 'Appraisal Type',
                'url' => 'appraisaltype',
                'icon' => '<i class=\'nav-icon las la-project-diagram\'></i>',
                'permission' => 'appraisal_types_list',
                'parent_id' => 9,
                'lft' => 47,
                'rgt' => 48,
                'depth' => 2,
                'created_at' => '2021-01-29 02:51:46',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            54 => 
            array (
                'id' => 56,
                'label' => 'Appraisal Interp.',
                'url' => 'appraisalinterpretation',
                'icon' => '<i class=\'nav-icon las la-award\'></i>',
                'permission' => 'appraisal_interpretations_list',
                'parent_id' => 9,
                'lft' => 45,
                'rgt' => 46,
                'depth' => 2,
                'created_at' => '2021-01-29 03:12:19',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            55 => 
            array (
                'id' => 57,
                'label' => 'Offence Classif.',
                'url' => 'offenceclassification',
                'icon' => '<i class=\'nav-icon las la-grimace\'></i>',
                'permission' => 'offence_classifications_list',
                'parent_id' => 9,
                'lft' => 81,
                'rgt' => 82,
                'depth' => 2,
                'created_at' => '2021-02-08 20:06:19',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            56 => 
            array (
                'id' => 58,
                'label' => 'Gravity Of Sanction',
                'url' => 'gravityofsanction',
                'icon' => '<i class=\'nav-icon las la-dizzy\'></i>',
                'permission' => 'gravity_of_sanctions_list',
                'parent_id' => 9,
                'lft' => 71,
                'rgt' => 72,
                'depth' => 2,
                'created_at' => '2021-02-09 18:51:28',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            57 => 
            array (
                'id' => 59,
                'label' => 'Offence & Sanction',
                'url' => 'offenceandsanction',
                'icon' => '<i class=\'nav-icon las la-book-reader\'></i>',
                'permission' => 'offence_and_sanctions_list',
                'parent_id' => 53,
                'lft' => 35,
                'rgt' => 36,
                'depth' => 2,
                'created_at' => '2021-02-09 19:07:27',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            58 => 
            array (
                'id' => 60,
                'label' => 'Shift Schedule',
                'url' => 'shiftschedules',
                'icon' => '<i class=\'nav-icon las la-calendar\'></i>',
                'permission' => 'shift_schedules_list',
                'parent_id' => 9,
                'lft' => 97,
                'rgt' => 98,
                'depth' => 2,
                'created_at' => '2021-02-12 20:40:44',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            59 => 
            array (
                'id' => 61,
                'label' => 'Daily Time Records',
                'url' => NULL,
                'icon' => '<i class=\'nav-icon las la-hourglass-half\'></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 40,
                'rgt' => 43,
                'depth' => 1,
                'created_at' => '2021-02-12 20:44:32',
                'updated_at' => '2021-02-19 00:36:07',
            ),
            60 => 
            array (
                'id' => 62,
                'label' => 'Employee Shift',
                'url' => 'employeeshiftschedule',
                'icon' => '<i class=\'nav-icon las la-business-time\'></i>',
                'permission' => 'employee_shift_schedules_list',
                'parent_id' => 61,
                'lft' => 41,
                'rgt' => 42,
                'depth' => 2,
                'created_at' => '2021-02-18 21:51:18',
                'updated_at' => '2021-02-19 00:36:07',
            ),
        ));
        
        
    }
}